title: Library Book Management System
description: Manages adding,issuing,searching and returning of books in a library.

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache


relative_links:
  enabled: true
  collections: true
include:
 - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme: pages-themes/dinky@v0.2.0
#theme: minimal-mistakes-jekyll
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
